name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:
  assemble-jobs:
    strategy:
      fail-fast: true
      matrix:
        jdk-version:
          - 21
        jdk-distribution:
          - temurin
    uses: ./.github/workflows/assemble-jobs.yaml
    with:
      jdk-version: ${{ matrix.jdk-version }}
      jdk-distribution: ${{ matrix.jdk-distribution }}

  test-jobs:
    strategy:
      fail-fast: true
      matrix:
        jdk-version:
          - 21
        jdk-distribution:
          - temurin
    uses: ./.github/workflows/test-jobs.yaml
    with:
      jdk-version: ${{ matrix.jdk-version }}
      jdk-distribution: ${{ matrix.jdk-distribution }}
