name: Open release pull-request jobs

on:
  workflow_call:
    inputs:
      release-type:
        type: string
        required: true
    secrets:
      ACCESS_ID:
        required: true
      ACCESS_PRIVATE_KEY:
        required: true

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  release-pr:
    runs-on: ubuntu-latest
    steps:
      - id: access-token
        name: Access token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.ACCESS_ID }}
          private_key: ${{ secrets.ACCESS_PRIVATE_KEY }}

      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.access-token.outputs.token }}

      - id: update-changelog
        name: Update changelog
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: bump
          version: ${{ inputs.release-type }}

      - id: update-manifest
        name: Update manifest files
        run: |
          sed -i -E '/^version =/s/=.*/= "${{ steps.update-changelog.outputs.version }}"/g' build.gradle*

      - id: commit-changes
        name: Commit changes
        run: |
          git config user.name "makerelease"
          git config user.email "makerelease@users.noreply.github.com"
          
          git add .
          git commit -m "update manifest files"
          git push

      - id: open-pr
        name: Open pull-request
        run: |
          gh pr create \
          --title "Release ${{ steps.update-changelog.outputs.version }}" \
          --body "${{ steps.update-changelog.outputs.release-notes }}"
        env:
          GH_TOKEN: ${{ steps.access-token.outputs.token }}
